services:
  gitlab-ce:
    image: gitlab/gitlab-ce:17.3.0-ce.0
    restart: always
    environment:
      TZ: Asia/Shanghai
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1:22345'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['gitlab_shell_ssh_port'] = 12345
        gitlab_rails['initial_root_password'] = "SdoBloodLine666?!"
        registry_external_url 'http://127.0.0.1:32345'
    ports:
      - "12345:22"
      - "22345:22345"
      - "32345:32345"
    volumes:
      - gitlab-ce-config-directory:/etc/gitlab
      - gitlab-ce-logs-directory:/var/log/gitlab
      - gitlab-ce-data-directory:/var/opt/gitlab
    shm_size: '256m'
    networks:
      - gitlab-tier
volumes:
  gitlab-ce-config-directory:
  gitlab-ce-logs-directory:
  gitlab-ce-data-directory:
networks:
  gitlab-tier:
